import { PoemOrStoryType } from "../types/type";

export const NancyInFAHLand: PoemOrStoryType = {
  id: 12,
  author: "JF",
  title: "Nancy In FAH-land",
  context:
    "A blue door in one of Arms theater tours and all the possible things that could be behind it.",
  social: { ig: "@jelefili" },
  content: `
  It was a warm and sunny day and Nancy was going home on her usual way. Suddenly she noticed a little blue door, she had never seen before. She was curious to what would lay behind it. So, she pushed down the handle and to her surprise the door was unlocked. Though as she had already opened it a tiny bit, her mother’s words crossed her mind. Remembering her not to dilly dally and to be home at time for dinner.

Pricked by the feeling of guilt Nancy stopped her doing. She stood there, still holding the doorknob, and deliberated if she should just come back another day or risk it now. Suddenly she felt something brush against her leg. She looked down just in time to see a little hoglet squeeze itself through the small door opening and vanish in the dark behind the blue door.

She was startled for a moment, unsure if she had really just heard a rushed “Thanks” from the little pig passing her by, with dark curly hair and a blue bow-tie around its neck. Then curiosity won, wiping away all of her mother’s words and her concerns and Nancy ran after the little animal. She came through a dark hallway that ended in a little room. In it there was just one desk in front of a big window and a whole bunch of people lining up to get to it. At the moment two men were sitting at the desk. One of them was wearing a shirt that was so creased that Nancy wondered if it had been chewed by a cow. He tried to make a joke, but quickly stopped, when he saw his anxious friend.

“Before granting you entry to FAH-land, you must first answer these simple questions,” the guy opposite them said in an accent Nancy had never heard in her life. Then he began asking them all sorts of things, the girl couldn’t hear anymore, since she had spotted the hoglet’s little curly tail in the crowd and went after it. Though just as she was about to follow it through a wide-open door, that had FAH-land written above it, a guy in a green sports jersey stepped in her way.

He wanted to go through the same door, but two guys stopped him. They asked for an ID and after looking at it one of them said, “Sorry mate. Regulars only,” and sent him away.

Just as he left, murmuring he would go to Canada instead, a small curly man approached the bouncers. He wanted to talk to the taller one of them, but he just told him, “Sorry mate, not tonight.” Though the man was persistent and didn’t want to leave. The bouncers were so occupied with him, that they didn’t notice the young girl sneaking pass them and enter FAH-land in the search of the little pig.

Walking on a narrow blue brick road leading through a little forest she remembered her last school trip where they were collecting things for a nature table. That day Adam didn’t want to hold her hand and Mr. O’Neill bored them all with the school guidelines he always carried with him. Though she had fun playing Hide and Seek. She wondered if she could impress Adam or maybe the new boy Paul, if she showed them the talking hoglet with the bow-tie. She was deep in her thoughts, when she heard a swooshing beside her. In the hope that it was the hoglet Nancy turned around, but it was just a man with raised arms wearing a grey cap and scarf. He moved his arms left and right and made a swoosh sound.

“Excuse me, have you maybe seen a little hoglet with a bow-tie?” Nancy asked, ignoring the man’s strange behaviour. Though he just kept swooshing and after she had tried another time to get his attention, she gave up and continued her way.

Until she heard, “What, no standing ovations for the great Richard Chandley III and his outstanding performance of a tree?” It was the man with the grey cap looking offended at her. He wanted to add something, but he was interrupted by a man from the other side of the path “That’s what you call a performance? Pathetic!”

“How dare you, insult the great Richard Chandley like that! What do you know about the real art of drama, you clown? Look at you, you couldn’t even portray a tree in a panto,” Richard Chandley replied. Nancy thought that the other man at least looked more like a tree or the nature, since he had a jacket with flowers on and for some reason, he also had a bird house on his head. She wanted to ask them about the hoglet, but she quickly realized that there was no point, since they had turned their argument into a battle of tree performances. And trees don’t talk, they only swoosh in the wind. So, Nancy just continued her way on the blue brick road, still looking for the hoglet. She hadn’t gotten far, when she heard someone giggle. She looked to her right and there was a scruffy-looking man lying in a ditch. He was laughing and when he saw her asking face, he told her “Well done girl, I was waiting for someone to pass those so-called artist imitating nature. I knew they couldn’t help but to show off and that always ends in the most hilarious fight. So, thanks for that. Is there anyway I can show my gratitude?”

Nancy needed a moment to even understand the man, since he was speaking very fast. But eventually she understood and so, she asked him, if he had seen the little hoglet and if he could tell her where to find it. He smiled and gave her some directions, that he had to repeat a second time, until Nancy had fully comprehended them. Though he didn’t seem to mind that. It was more like he enjoyed her confused face and she could still hear him giggle when she walked away.

After a while Nancy reached a little house with a blue roof and door and a wild flower garden in front of it. She just wanted to knock, when a blond guy came out of the house. He almost ran her over, looking for something. “Where is it? Where is it?” he asked himself, while turning over every pot and looking under every stone. He was just on his knees combing through the flowers, when a window opened and a lanky guy said smiling “I found it,” holding a little furry ball in the air. The blonde man turned hopeful around, but after one look he just shook his head saying “No, that’s a fluffy joke. I need the real one. Oh, how can’t I remember. Why does my head have to be like a sieve?” before he continued his search.

“Oh, hello! Who are you?” the man at the window noticed Nancy, who was still standing in front of the door.
The girl introduced herself to which the man replied “Hello Nancy, I am Arms and this is my friend Foil.” Nancy thought that those were strange names, but she just pushed that away and politely asked if they had seen the hoglet with the bow-tie. “Ah, Hog is probably prowling around somewhere,” the man in the flowers answered absently, before he gave up and sat down.

“I remember. I don’t remember. I remember. I don’t remember,” he was saying sadly, while picking petals from a daisy. Nancy felt sorry for him and asked where he had seen the joke, she assumed he was looking for, the last time. She had never heard of someone losing a joke, but she wasn’t a sceptical person and she just had to help the desperate man. 
He looked at her with teary eyes and said “I don’t remember”, before he started crying. As Nancy pet him on his shoulder to console him, she noticed that his tears looked like liquid tin foil and she could also see herself in his cheek like she was looking into a spoon. Meanwhile the other guy had joined them and told his friend they would find another joke and tried to come up with one to cheer him up. But that made things just worse, so he scrummaged through his pockets to find a tissue for him. Nancy looked dazzled at the lanky guy, since he was doing that while still petting the thing they called a fluffy joke. Then she realized that he had not two, but six arms. She was still wondering about that, when he asked her if she knew any jokes. Surprised she answered that she only knew one Mr O’Neill had once told them in an attempt to be funny. That made the foil-like guy look up, so Nancy said, “Ok, the joke goes like this. Knock, knock, knock.” The girl stopped there, because she heard laughter coming from under a tree in a corner. All three turned around, but couldn’t see anything, because of the flowers. Nancy started again, but this time she couldn’t even say the third knock, since she was interrupted after the second. Slightly annoyed, she tried it once more, but the laughter ruined it again. So, she went to the tree to see who was disturbing her and to her surprise, it was the same guy that had told her where she could find the hoglet’s home. His face was red from laughter and she just wanted to ask him what was so funny, when the six-armed-men said, “There you are Hog. I knew I recognized that laughter.”

“Wait, if that’s your Hog, then that’s not the hoglet I was looking for. You lied to me”, she said crossly to the man under the tree. “No! You asked me where you could find a hoglet with a blue bow-tie and I told you. You didn’t ask if it was me,” the curly man answered grinning and in the blink of an eye he was gone and instead the little hoglet was lying in the grass, shaking with laughter. Now all three of them were laughing and the tin foil tears were now caused by laughter and not despair. Then they tried to repeat Nancy’s joke themselves but could barely get the first word out. She found it strange that they were laughing at not even half a joke, but actually just one word, though eventually the contagious laughter reached her too and soon enough they were all laughing.

Suddenly she heard someone call her name, but she couldn’t see anybody. The silly men were still laughing when she bowed down to a little blue door at the bottom of the tree. Someone behind it was saying her name.

She pushed the door open and in the next moment she was back on the pavement next to the brick wall. Her friend Adam was looking down at her and asked what she was doing on the ground. Nancy slowly stood up and looked around. There wasn’t a blue door in the wall anymore and when she asked Adam if he had seen it, he just shook his head and asked, “What blue door?” “Never mind,” Nancy answered, suddenly unsure if the door had ever existed. Adam just shrugged his shoulders and told her to hurry up or they would get in trouble with their mothers.

She followed him, still wondering if the hoglet and FAH-land were real or if she just had a sunstroke, causing this strange dream. Though when she passed a shop window and saw her reflection in it, she stopped and couldn’t help but smile. Her shirt had been plain this morning, but now she could see the letters F, A and H written on the top corner of it and when she looked at them it was like she could hear laughter.
  `,
};
